import { siteConfig } from '@/config/site';

/**
 * Sitemap documents are generated by the backend (single source of SEO truth)
 * but must be served from the *public site origin*, because a sitemap has to
 * live on the same host as the URLs it lists. The API is a separate origin in
 * production, so these route handlers re-expose the backend documents at the
 * canonical host without duplicating any SEO logic.
 */
export const SITEMAP_REVALIDATE_SECONDS = 3600;

const XML_HEADERS = {
  'content-type': 'application/xml; charset=utf-8',
  'cache-control': `public, max-age=${SITEMAP_REVALIDATE_SECONDS}, stale-while-revalidate=600`,
};

/**
 * Streams a backend sitemap document to the public origin.
 *
 * Returns 502 rather than an empty 200 when the backend is unavailable: a
 * crawler receiving a valid-XML-but-empty response could interpret a transient
 * outage as "this site has no URLs" and drop pages from the index.
 *
 * Genuine client errors from upstream (an unknown partition name, an invalid
 * page number) are passed through as-is, so a bad URL yields 404/400 instead of
 * masquerading as an upstream failure.
 */
export async function proxyBackendSitemap(path: string): Promise<Response> {
  const upstream = process.env.API_URL ?? siteConfig.apiUrl;
  const url = `${upstream.replace(/\/$/, '')}/api/v1${path}`;

  try {
    const response = await fetch(url, { next: { revalidate: SITEMAP_REVALIDATE_SECONDS } });
    if (response.status >= 400 && response.status < 500) {
      return new Response(null, { status: response.status, headers: { 'cache-control': 'no-store' } });
    }
    if (!response.ok) {
      return new Response('Sitemap temporarily unavailable\n', {
        status: 502,
        headers: { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'no-store' },
      });
    }
    return new Response(await response.text(), { headers: XML_HEADERS });
  } catch {
    return new Response('Sitemap temporarily unavailable\n', {
      status: 502,
      headers: { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'no-store' },
    });
  }
}

/** Only allow known partition filenames; anything else is a genuine 404. */
export function isValidPartitionFile(file: string): boolean {
  return /^[a-z0-9-]+\.xml$/.test(file);
}